#!/usr/bin/env python3
import os
from clate_core import clate_core

CLATE_JSON = os.getenv("HOME") + '/.clate.json'


def main():
    if not os.path.exists(CLATE_JSON):
        print("[ ERR ] {0} is not existed.".format(CLATE_JSON))
        return

    params = clate_core.parse()
    if clate_core.check_param(params):
        dirMgr = clate_core.DirManager()
        interactor = clate_core.Interactor(dirMgr)
        clate = clate_core.Clate(dirMgr, interactor)

        clate_core.clate_main(clate, params)

    print("[ INF ] clate is closed")


if __name__ == '__main__':
    main()
