#!/bin/bash
DIR=/Workspace/.vscode/
FILE=/Workspace/.vscode/settings.json
if [ -d "$DIR" ]; then
    if [ ! -f "$FILE" ]; then
        su -m - $UNAME -c "cp $HOME/settings.json $DIR/"
    fi
else
    mkdir $DIR
    chown $UID:$GID $DIR -R
    su -m - $UNAME -c "cp $HOME/settings.json $DIR/"
fi
